#ifndef _MULTIFX_ERRORS_H
#define _MULTIFX_ERRORS_H

#define ERROR_BIAS_VAL (0)
#define MULTIFX_OPEN_DEV_FAILURE (ERROR_BIAS_VAL-2)
#define MULTIFX_GET_INFO_FAILURE (ERROR_BIAS_VAL-3)
#define MULTIFX_GET_RAWDATA_FAILURE (ERROR_BIAS_VAL-4)
#define MULTIFX_SNDCTL_DSP_GETCAPS_FAILURE (ERROR_BIAS_VAL-5)
#define MULTIFX_FULLDUPLEX_NOTSUPPORTED (ERROR_BIAS_VAL-6)
#define MULTIFX_SUGG_BUFF_FAILURE (ERROR_BIAS_VAL-7)
#define MULTIFX_SUGG_SNDCTL_DSP_CHANNELS_FAILURE (ERROR_BIAS_VAL-8)
#define MULTIFX_SET_STEREO_FAILURE (ERROR_BIAS_VAL-9)
#define MULTIFX_SET_MONO_FAILURE (ERROR_BIAS_VAL-10)
#define MULTIFX_SET_BIT_FAILURE (ERROR_BIAS_VAL-11)
#define MULTIFX_SET_16BIT_NOTSUPPORTED (ERROR_BIAS_VAL-12)
#define MULTIFX_OPPOSITE_ENDIANESS (ERROR_BIAS_VAL-13)
#define MULTIFX_SNDCTL_DSP_SPEED_FAILURE (ERROR_BIAS_VAL-14)
#define MULTIFX_SET_SAMPLE_RATE_FAILURE (ERROR_BIAS_VAL-15)
#define MULTIFX_SNDCTL_DSP_GETBLKSIZE_FAILURE (ERROR_BIAS_VAL-16)
#define MULTIFX_BUFF_DIM_ERROR (ERROR_BIAS_VAL-17)
#define MULTIFX_SETPOLICY_FAILURE (ERROR_BIAS_VAL-18)
#define MULTIFX_CALL_NOTSUPPORTED (ERROR_BIAS_VAL-19)
#define MULTIFX_RD_FAILURE (ERROR_BIAS_VAL-20)
#define MULTIFX_WR_FAILURE (ERROR_BIAS_VAL-21)

#endif


