#ifndef _MULTIFX_OSS_UTILS_H
#define _MULTIFX_OSS_UTILS_H


#include <MULTIFX_typedef.h>



MULTIFX_API_RET char2short_mono (MULTIFX_CHAR_T *in_buf, MULTIFX_INT16_T *w_buf,MULTIFX_UINT32_T frag_size);
MULTIFX_API_RET char2short_stereo (MULTIFX_CHAR_T *in_buf, MULTIFX_INT16_T *w_bufL, MULTIFX_INT16_T *w_bufR,MULTIFX_UINT32_T frag_size);
MULTIFX_API_RET short2char_mono (MULTIFX_CHAR_T *out_buf, MULTIFX_INT16_T *w_buf,MULTIFX_UINT32_T frag_size);
MULTIFX_API_RET short2char_stereo (MULTIFX_CHAR_T *out_buf, MULTIFX_INT16_T *w_bufL, MULTIFX_INT16_T *w_bufR,MULTIFX_UINT32_T frag_size);
MULTIFX_API_RET read_device_data (MULTIFX_INT32_T fd,MULTIFX_CHAR_T *rbuffer,MULTIFX_INT32_T fragsize);
MULTIFX_API_RET write_device_data (MULTIFX_INT32_T fd,MULTIFX_CHAR_T *wbuffer,MULTIFX_INT32_T fragsize);
MULTIFX_API_RET char2float_stereo (MULTIFX_CHAR_T *in_buf, MULTIFX_FLOATING_T *wbufL_L, MULTIFX_FLOATING_T *wbufFL_R,MULTIFX_UINT32_T frag_size);
MULTIFX_API_RET float2char_stereo (MULTIFX_CHAR_T *out_buf, MULTIFX_FLOATING_T *wbufFL_L, MULTIFX_FLOATING_T *wbufFL_R,MULTIFX_UINT32_T frag_size);
MULTIFX_API_RET int162float_stereo (MULTIFX_INT16_T *rbuf_L,MULTIFX_INT16_T *rbuf_R, MULTIFX_FLOATING_T *rbuf_FL_L,MULTIFX_FLOATING_T *rbuf_FL_R,MULTIFX_INT32_T fragsize);
MULTIFX_API_RET float2int16_stereo (MULTIFX_FLOATING_T *wbuf_FL_L,MULTIFX_FLOATING_T *wbuf_FL_R,MULTIFX_INT16_T *wbuf_L,MULTIFX_INT16_T *wbuf_R, MULTIFX_INT32_T fragsize);

#endif
