#ifndef _FX_LIBRARY_UTILS_H
#define  _FX_LIBRARY_UTILS_H

#include <MULTIFX_typedef.h>

MULTIFX_API_RET filter_DII_T (MULTIFX_FLOATING_T *in, MULTIFX_FLOATING_T *out, MULTIFX_FLOATING_T *a, MULTIFX_UINT32_T order, MULTIFX_FLOATING_T *b, MULTIFX_FLOATING_T *state,MULTIFX_UINT32_T len_frame);
MULTIFX_API_RET filter_time_varying_DII_T (MULTIFX_FLOATING_T *in, MULTIFX_FLOATING_T *out, MULTIFX_FLOATING_T *a, MULTIFX_UINT32_T order, MULTIFX_FLOATING_T *b, MULTIFX_FLOATING_T *state,MULTIFX_UINT32_T len_frame);


#endif
